### ISSUE TITLE
Inconsistent behavior when toggling value using checkbox

### ISSUE THREAD

**Issue by jdheeter** [jviotti/electron-json-storage#16]
I need to save user preferences when the checkbox is used. I found that after I press the checkbox 1 -4 times I get an error in console with each click "Uncaught Error: Invalid data"

I assume this has something to do with FS or async. If I stop clicking and wait 5 - 10 seconds, then I find that sometimes it will work correctly and sometimes it will not.  Any suggestions for an improved implementation?

```js
$('#KeySwitch').click(function() {
      storage.set('keySwitch', { keySwitch:this.checked })
      keySwitchB = this.checked
      console.log(keySwitchB);
      storage.get('keySwitch',function(error, data){
        if (error) throw error;
        console.log(data.keySwitch);
      })
    });
```

```html
<input type="checkbox" id="KeySwitch" class="mdl-checkbox__input" checked />
```

**Comment by jviotti** [comment]
Hi @jdheeter ,

Thanks for reaching out! I believe the issue is that you're not waiting for `.set()` to complete before calling `.get()` which causes a race condition between both functions which could explain the weird behaviour you're describing. Can you try the following?

```js
$('#KeySwitch').click(function() {
  storage.set('keySwitch', { keySwitch:this.checked  }, function(error) {
    if (error) throw error;

    keySwitchB = this.checked
    console.log(keySwitchB);

    storage.get('keySwitch',function(error, data){
      if (error) throw error;
      console.log(data.keySwitch);
    })
  })
});
```

Let me know if this doesn't solve the issue, and I'll start a debugging session on this module itself!

**Comment by jdheeter** [comment]
That solved my issue, thanks for your help!

**Comment by jviotti** [comment]
Awesome to hear that, have a great day!
