### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by roldyclark** [jviotti/electron-json-storage#37]
I keep getting an undefined from .get. JSON's are all there.

**Comment by jviotti** [comment]
Can I test this somewhere? There is not much I can help with without an
actual application I can clone (even if its a minimal gist that
reproduces the issue).

At first sight, this could be caused by two things:

- Invalid or messed up JSON in the data directory (you can try purging
  all data and recreate again to confirm this theory).

- Some obscure issue in this module that is not being covered by the
  test suite.

Let me know!

On Mon, Dec 05, 2016 at 09:48:00AM -0800, roldyclark wrote:
> I keep getting an undefined from .get. JSON's are all there.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jviotti/electron-json-storage/issues/37

-- 
Juan Cruz Viotti
Software Engineer

**Comment by roldyclark** [comment]
function load() {
  smalltalk.prompt('Save', 'Enter Project Name', ' ').then(function(value) {
    var array = JSON.parse(storage.get(value))
    console.log(array);
}, function() {
    console.log('cancel');
});
}

I've got this function- I'm inexperienced with JSON but I tried parse, stringify, neither - always undefined.

Here's a JSON:
{"video":"/Applications/MAMP/htdocs/media/1.m4v","audio":[["/Applications/MAMP/htdocs/media/reversewalk.wav","/Applications/MAMP/htdocs/media/reversewalk.wav"],["/Applications/MAMP/htdocs/media/reversewalk.wav","/Applications/MAMP/htdocs/media/reversewalk.wav"]]}

**Comment by roldyclark** [comment]
this is an array of video objects, they will be assigned to var vidArray - just console.logging for now

**Comment by roldyclark** [comment]
![screen shot 2016-12-05 at 3 49 50 pm](https://cloud.githubusercontent.com/assets/20400349/20901850/7de34a18-bb02-11e6-9870-260001d5e1e9.png)

**Comment by roldyclark** [comment]
missing ; in copypaste but it's in my code and not the problem.

**Comment by roldyclark** [comment]
I solved it. but new problem. .DS-Store shows up on

**Comment by jviotti** [comment]
```js
var array = JSON.parse(storage.get(value))
```

This is not right. `storage.get()` is an asynchronous function, and should be used like this (see also the examples in the README):

```js
storage.get(value, function(error, result) {
    if (error) {
        // handle error
    }

    var array = JSON.parse(result);
});
```
